In [9]:
import os
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import scipy.stats as stats

import seaborn as sns

from tqdm import tqdm 
from datetime import datetime, time

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

In [7]:
filesdir = '/mnt/c/Users/Aryuna/Desktop/tuturu'
os.listdir(filesdir)

['0605024',
 'clickhouse_v7_AR_2404.html',
 'clickhouse_v7_AR_2404.ipynb',
 'clickhouse_v7_AR_2504.html',
 'demand_model_v01_02042021_4438depth(1).csv',
 'df_big_query_session.parquet',
 'df_ord_based.parquet',
 'pelican_mobile_v06_30032022_dm_7103up5.csv',
 'tutut-20240531T080550Z-001.zip']

In [13]:
os.listdir(filesdir+'/0605024')

['merged_final_sorted_v2_0605.csv',
 'orders_gran0_0605.csv',
 'orders_gran1_0605.csv',
 'orders_gran2_0605.csv',
 'session_gran0_0605.csv',
 'session_gran1_0605.csv',
 'session_gran2_0605.csv',
 'session_query_small_all.parquet']

In [11]:
dates=pd.to_datetime('2024-04-19')
print(dates)

# Основные функции 
def travel_time(ser):
    """test
    Экспресс или нет
    """ 
    if ser <=   5:
        return 'экспресс'
    else:
        return 'долгий'

# ремапер имен типов вагонов
cat_remap={'plazcard':'плац', "sedentary":"сид","coupe":"куп", 'lux':'св', 'soft':'св','common':'сид' }

2024-04-19 00:00:00

In [14]:
#df=pd.read_parquet(os.path.join(filesdir, 'df_based_evg.parquet'))
df_ord=pd.read_parquet(os.path.join(filesdir,'df_ord_based.parquet'))

In [15]:
df_ord

,order_id,state,created_at,train_number,car_category,original_departure_datetime,arrival_date,departure_date,additional_data_is_train_firm,additional_data_train_name,departure_station_id,arrival_station_id,departure_station_name,arrival_station_name,additional_data_train_arrival_station_number,additional_data_train_departure_station_number,additional_data_remaining_seats,category_data_placement_details_seats,additional_data_user_id,additional_data_session_id,additional_data_service_class,additional_data_top_seats,additional_data_price_on_detail,additional_data_bottom_seats,total_amount,amount_for_tutu,rzd_amount,car_number,paid_tickets,category_data_requirements_not_near_wc,free_tickets,session_id,ab_var
0,76636993,paid,2024-04-09 00:30:29,089Ж,coupe,2024-04-17 02:36:00,2024-04-18 13:11:00,2024-04-17 02:36:00,0,,5077,1887,Волгоград-1,Санкт-Петербург-Главн.,2004001,2020500,80,"[{""gender_type"":null,""is_near_ws"":null,""level""...",31656832.0,7264499b-7ccf-422b-8c5a-3f7dc21fbf92,2Ш,2,19165.67,1,19165.67,18744.03,16566.3,11,3,0.0,0,7264499b-7ccf-422b-8c5a-3f7dc21fbf92,off
1,76637228,paid,2024-04-09 00:47:43,157В,plazcard,2024-05-01 23:28:00,2024-05-02 10:57:00,2024-05-01 23:28:00,0,None,1889,36646,Санкт-Петербург-Витеб.,Москва ВК Восточный,2001025,2004003,49,"[{""gender_type"":null,""is_near_ws"":null,""level""...",33206626.0,3f874212-fbe4-465d-a003-59acb1fd7754,3Б,1,5860.92,1,6264.92,6127.09,4864.6,02,2,0.0,0,3f874212-fbe4-465d-a003-59acb1fd7754,down10
2,76637461,paid,2024-04-09 01:17:17,259С,coupe,2024-06-10 23:05:00,2024-06-12 21:05:00,2024-06-10 23:05:00,0,,12077,1887,Анапа,Санкт-Петербург-Главн.,2004001,2064188,37,"[{""gender_type"":null,""is_near_ws"":null,""level""...",12782311.0,f7050823-960f-4817-8678-b0c928af4767,2К,0,23750.14,2,23750.14,23227.64,21502.8,05,2,0.0,0,f7050823-960f-4817-8678-b0c928af4767,off
3,76638661,paid,2024-04-09 05:27:57,107Ж,plazcard,2024-04-19 23:10:00,2024-04-22 13:27:00,2024-04-21 14:09:00,1,Самара,6666,6963,Екатеринбург Пасс.,Нижневартовск-1,2030308,2030000,17,"[{""gender_type"":null,""is_near_ws"":null,""level""...",54550466.0,ed261023-ce0c-4353-b1a4-18a6b848d8f7,3Б,1,3340.53,0,3340.53,3267.04,3005.1,06,1,0.0,0,ed261023-ce0c-4353-b1a4-18a6b848d8f7,up10
4,76639201,paid,2024-04-09 06:22:53,011Ч,coupe,2024-04-15 10:10:00,2024-04-16 10:09:00,2024-04-15 13:34:00,0,,2603,1892,Апатиты-1,Санкт-Петербург Ладож.,2004006,2004717,113,"[{""gender_type"":null,""is_near_ws"":null,""level""...",33768806.0,5c09a96e-de40-4734-b7f1-8f0d5f868d44,2А,1,4425.26,0,4425.26,4327.90,3929.7,01,1,0.0,0,5c09a96e-de40-4734-b7f1-8f0d5f868d44,up10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136551,77079246,paid,2024-04-17 23:52:06,126С,plazcard,2024-04-22 13:40:00,2024-04-23 19:40:00,2024-04-22 13:40:00,0,,12008,177,Новороссийск,Москва Казанская,2000003,2064110,42,"[{""gender_type"":null,""is_near_ws"":null,""level""...",54912495.0,84130424-6bcf-407d-8883-a3bd5ceef02f,3Б,0,3957.66,1,4359.66,4263.75,3704.6,05,1,0.0,0,84130424-6bcf-407d-8883-a3bd5ceef02f,up10
136552,77079274,paid,2024-04-17 23:53:03,149Г,sedentary,2024-04-22 16:20:00,2024-04-23 04:20:00,2024-04-23 00:19:00,0,None,11182,177,Муром-1,Москва Казанская,2000003,2060370,62,"[{""gender_type"":null,""is_near_ws"":null,""level""...",32201138.0,a9e9b075-b916-4726-af5c-b59196fc8702,2С,0,754.05,0,754.05,737.46,664.6,07,1,0.0,0,a9e9b075-b916-4726-af5c-b59196fc8702,up10
136553,77079294,paid,2024-04-17 23:54:05,041С,sedentary,2024-04-19 15:40:00,2024-04-19 19:30:00,2024-04-19 15:40:00,0,,5078,5241,Астрахань,Владимировка,2020884,2020600,29,"[{""gender_type"":null,""is_near_ws"":null,""level""...",32915682.0,8dd78105-2358-41e6-8f1d-940f7107c9d3,2Ж,0,1188.43,0,1049.80,1026.70,891.5,04,2,0.0,0,8dd78105-2358-41e6-8f1d-940f7107c9d3,down10
136554,77079298,paid,2024-04-17 23:54:23,715М,sedentary,2024-04-22 07:15:00,2024-04-22 11:21:00,2024-04-22 07:15:00,0,Ласточка,180,344,Москва Белорусская,Смоленск Центральный,2000170,2000006,120,"[{""gender_type"":null,""is_near_ws"":null,""level""...",12890821.0,73171023-7404-463b-bdf0-211c5855bf56,2Р,0,1750.94,0,1750.94,1712.42,1430.1,04,1,0.0,0,73171023-7404-463b-bdf0-211c5855bf56,up10
136555,77079332,paid,2024-04-17 23:56:37,092М,plazcard,2024-04-18 23:52:00,2024-04-19 08:18:00,2024-04-18 23:52:00,0,ТАВРИЯ,177,4502,Москва Казанская,Придача (Воронеж Южный),2014496,2000003,66,"[{""gender_type"":null,""is_near_ws"":null,""level""...",25827963.0,cb031023-acb0-4611-ab39-6eb4bf777c3f,3Э,1,1843.03,0,1843.03,1802.48,1629.2,07,1,0.0,0,cb031023-acb0-4611-ab39-6eb4bf777c3f,up10